### ISSUE TITLE
Gist uploads rejected (since recently)

### ISSUE THREAD

**Issue by gjoseph** [hohl/sourcedrop-osx#10]
I've been getting this error since a few days - i suspect a change on github's side ?
````
{
    Response = "{\"message\":\"Invalid request.\\n\\nNo subschema in \\\"anyOf\\\" matched.\",\"documentation_url\":\"https://developer.github.com/v3\"}";
    SharingService = "GIST (GitHub)";
    StatusCode = 422;
    StatusMessage = "HTTP/1.1 422 Unprocessable Entity";
    UploadName = where;
}
````

**Comment by hohl** [comment]
Thanks for reporting this issue. I'll have a look at it soon.

**Comment by hohl** [comment]
It looks like GitHub changed the way how it processes booelan values. SourceDrop sends them as 0 and 1s, however when changing it to "true" and "false" everything works.

**Comment by gjoseph** [comment]
and already released !? Brilliant, thanks ! :)

**Comment by hohl** [comment]
Yes, release 1.6. Available for download on GitHub immediately and submitted to the App Store yesterday.
