### ISSUE TITLE
Odd bubble notification since 1.6

### ISSUE THREAD

**Issue by gjoseph** [hohl/sourcedrop-osx#11]
Following #10, i installed 1.6; the upload to Gist indeed works now, but I get the following in the notification bubble:

![screen shot 2015-03-11 at 12 25 29](https://cloud.githubusercontent.com/assets/74627/6598177/18d27166-c802-11e4-9e06-e89dc20dda90.png)

**Comment by hohl** [comment]
Thanks for the notice. Looks like I need to have another look at that issue.

**Comment by gjoseph** [comment]
In case that makes a difference, I had 1.5 installed via the App Store but I installed 1.6 "manually" (i.e downloaded the .app from github)

**Comment by hohl** [comment]
Please test SourceDrop 1.6.1. It shouldn't happen anymore there.

**Comment by gjoseph** [comment]
Perfect, thanks a lot !
